server:
   context-path: /micro
   port: 8080
 
spring:
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://cap-sg-prd-2.integration.ibmcloud.com:17413/inventorydb
     username: dbuser
     password: Pass4dbUs3R
   jpa:
     database: MYSQL